#!/usr/bin/env python3
"""Targeted oversampling of rare-class training images (Block 12 ablation).

Usage:
    python scripts/prepare_oversampled_train.py \\
        --rare-classes "Bacterial leaf blight" "Bacterial panicle blight" "False smut" "Leaf roller" "Narrow brown" \\
        --multiplier 3

Builds an oversampled TRAIN-ONLY dataset variant from the existing Block 5
prepared train manifest: any image containing at least one instance of a
designated rare class is included `--multiplier` total times, via
distinctly-named symlinks to the same underlying raw image (no byte
duplication, no synthetic data, the same real image is just seen more
often per epoch).

Validation and test data are NEVER touched: this script only ever writes
under `<output-dir>/train/`, and the generated `data.yaml` points `val:`/
`test:` at the ORIGINAL, unmodified `data/prepared/{valid,test}/images`
directories, literally the same files, guaranteeing zero contamination by
construction, not just by convention.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from agridata.dataset.mapping import CANONICAL_ID_TO_NAME  # noqa: E402


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build an oversampled train-only dataset variant.")
    parser.add_argument("--prepared-dir", default=Path("data/prepared"), type=Path)
    parser.add_argument("--output-dir", default=Path("data/prepared_oversampled"), type=Path)
    parser.add_argument("--rare-classes", nargs="+", required=True, help="Canonical class names to oversample.")
    parser.add_argument("--multiplier", type=int, default=3, help="Total occurrences for images containing a rare class (1=no change).")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    manifest_path = args.prepared_dir / "manifest_train.json"
    with manifest_path.open("r", encoding="utf-8") as f:
        manifest = json.load(f)

    images_dir = args.output_dir / "train" / "images"
    labels_dir = args.output_dir / "train" / "labels"
    images_dir.mkdir(parents=True, exist_ok=True)
    labels_dir.mkdir(parents=True, exist_ok=True)

    original_images_dir = (args.prepared_dir / "train" / "images").resolve()
    original_labels_dir = (args.prepared_dir / "train" / "labels").resolve()

    rare_set = set(args.rare_classes)
    oversampled_image_count = 0
    total_written = 0

    for entry in manifest:
        file_name = entry["file_name"]
        stem = Path(file_name).stem
        has_rare = any(ann["canonical_class"] in rare_set for ann in entry["annotations"])
        copies = args.multiplier if has_rare else 1
        if has_rare:
            oversampled_image_count += 1

        source_image = original_images_dir / file_name
        source_label = original_labels_dir / f"{stem}.txt"
        label_content = source_label.read_text(encoding="utf-8") if source_label.exists() else ""

        for i in range(copies):
            suffix = "" if i == 0 else f"_dup{i}"
            dest_image = images_dir / f"{stem}{suffix}{Path(file_name).suffix}"
            dest_label = labels_dir / f"{stem}{suffix}.txt"
            if dest_image.is_symlink() or dest_image.exists():
                dest_image.unlink()
            dest_image.symlink_to(source_image)
            dest_label.write_text(label_content, encoding="utf-8")
            total_written += 1

    lines = [
        "# Auto-generated by scripts/prepare_oversampled_train.py, do not hand-edit.",
        "# val/test point at the ORIGINAL prepared directories, unmodified, oversampling",
        "# only ever touches train/, guaranteeing zero evaluation-data contamination.",
        f"path: {args.output_dir.resolve()}",
        "train: train/images",
        f"val: {(args.prepared_dir / 'valid' / 'images').resolve()}",
        f"test: {(args.prepared_dir / 'test' / 'images').resolve()}",
        "",
        "names:",
    ]
    for canonical_id in sorted(CANONICAL_ID_TO_NAME):
        lines.append(f"  {canonical_id - 1}: {CANONICAL_ID_TO_NAME[canonical_id]}")
    (args.output_dir / "data.yaml").write_text("\n".join(lines) + "\n", encoding="utf-8")

    summary = {
        "rare_classes": args.rare_classes,
        "multiplier": args.multiplier,
        "original_train_images": len(manifest),
        "images_containing_rare_class": oversampled_image_count,
        "total_train_images_after_oversampling": total_written,
        "data_yaml": str(args.output_dir / "data.yaml"),
    }
    print(json.dumps(summary, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
